language: python
python:
  - 3.9

# Update pip to the latest version
before_install:
  - python --version
  - pip install -U pip

install:
  - pip install -r requirements.txt

script:
  - python -m unittest tests/angle_tests.py
  - python -m unittest tests/arc_tests.py
  - python -m unittest tests/centers_from_params_tests.py
  - python -m unittest tests/command_to_arc_tests.py
  - python -m unittest tests/marlin_command_tests.py
  - python -m unittest tests/marlin_commands_tests.py
  - python -m unittest tests/unit_convert_tests.py

deploy:
  provider: pypi
  username: "__token__"
  password: "$PYPI_TOKEN"
#  skip_cleanup: true
  on:
    branch: master